config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'memories/add', to: 'pages#add', as: :add
  get 'memories/board', to: 'memboard#board', as: :memboard
  get 'memories/profile', to: 'pages#profile', as: :profile

  get 'memories/databoard', to: 'pages#databoard', as: :databoard

  get 'memories/add/photo', to: 'pages#photo', as: :modal_photo
  get 'memories/add/video', to: 'pages#video', as: :modal_video
  get 'memories/add/quote', to: 'pages#quote', as: :modal_quote


  resources :memories, only: [:index, :create, :edit, :update, :destroy] do
    resources :stamps, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'test', to: 'pages#test'
  get 'test2', to: 'pages#test2'
  get 'test3', to: 'pages#test3'

end

app/views/shared/_dashboard.html.erb
<div class="dashboard-banner">
  <div class="total-memories">
    <h2>You currently have <%= pluralize @memories.count, "memory" %></h2>
  </div>
  <div class="d-none d-md-block d-lg-block">
    <div class="row">
      <div class="col-md-2 offset-md-2">
        <% count1 = [] %>
        <% @memories.each do |memory| %>
          <% if memory.memory_type == "spotify" %>
            <% count1 << memory %>
          <% end %>
        <% end %>
        <div class="box-viz">
          <div class="icon">
            <p><%= image_tag "music-icon.svg", class: "taille-petite" %></p>
          </div>
          <div class="count">
            <p><%= count1.length %></p>
            <p><%=  "Music".pluralize(count1.length) %></p>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <% count2 = [] %>
        <% @memories.each do |memory| %>
          <% if memory.memory_type == "photo" || memory.memory_type == "instagram" %>
            <% count2 << memory %>
          <% end %>
        <% end %>
        <div class="box-viz">
          <div class="icon">
            <p><%= image_tag "image-icon.svg", class: "taille-petite" %></p>
          </div>
          <div class="count">
            <p><%= count2.length %></p>
            <p><%=  "Image".pluralize(count2.length) %></p>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <% count3 = [] %>
        <% @memories.each do |memory| %>
          <% if memory.memory_type == "video" %>
            <% count3 << memory %>
          <% end %>
        <% end %>
        <div class="box-viz">
          <div class="icon">
            <p><%= image_tag "video-icon.svg", class: "taille-petite" %></p>
          </div>
          <div class="count">
            <p><%= count3.length %></p>
            <p><%=  "Video".pluralize(count3.length) %></p>
          </div>
        </div>
      </div>
      <div class="col-md-2">
        <% count4 = [] %>
        <% @memories.each do |memory| %>
          <% if memory.memory_type == "quote" %>
            <% count4 << memory %>
          <% end %>
        <% end %>
        <div class="box-viz">
          <div class="icon">
            <p><%= image_tag "citation-icon.svg", class: "taille-petite" %></p>
          </div>
          <div class="count">
            <p><%= count4.length %></p>
            <p><%=  "Quote".pluralize(count4.length) %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="sweet-alert-demo"></div>
<% end %>
<% if alert %>
  <div class="alert alert-danger red" role="alert" id="myAlert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_modalphoto.html.erb
<!-- MODAL PHOTO -->

<div class="modal fade bd-example-modal-lg" id="photo" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <div id="fermer-modal-ajout" data-toggle="modal" data-target=".bd-example-modal-lg" data-backdrop="static">
          <%= link_to add_path do%>
            <i class="fas fa-times"></i>
          <% end  %>
        </div>
        <div class="conteneur-modal-ajout">
          <h1 id='titre-ajout'>Add a photo memory</h1>
          <%= simple_form_for [@memory] do |f| %>
            <div class="row">
              <div class="col-xs-12 col-md-5">
                <div class="cadre-photo img-fluid" alt="Responsive image">
                  <%= cl_image_upload_tag(:image_id)%>
                </div>
              </div>
              <div class="col-xs-12 col-md-7">
                <%= f.input :memory_type, input_html: { id: 'special_categorie', value: "photo" }, as: :hidden, require: true  %>
                <%= f.input :title, label: 'Your photo name', require: true %>
                <%= f.input :description, label: 'Tell me more about this photo' %>
                <%= f.label 'Your stamps*', autofocus: true %>
                <div class="stamps-form">
                  <%= select_tag 'memory[stamps][]', options_for_select(Stamp.all.pluck(:title)), multiple: 'multiple', class: 'form-control select2'%>
                </div>
              </div>
              <div class="submit-add-button">
                <%= f.submit 'Add a memory', class: "btn boutton-rouge boutton-rouge-inside" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for(:js) do %>
  <script>
    $('#photo').modal('show');
    $(function() {
      if($.fn.cloudinary_fileupload !== undefined) {
        $("input.cloudinary-fileupload[type=file]").cloudinary_fileupload();
      }
    });

    function cloudinaryPreview() {
      $('.cloudinary-fileupload').bind('cloudinarydone', function(e, data) {
        console.log(data)
        $('.cadre-photo').html(
          $.cloudinary.image(data.result.public_id,
            { format: data.result.format, version: data.result.version,
              class: "img-fluid"})
        );
        $('.image_id').val(data.result.public_id);
        return true;
      });
    }
    cloudinaryPreview()
  </script>
<% end %>

app/views/shared/_modalquote.html.erb
<!-- MODAL QUOTE -->

<div class="modal fade bd-example-modal-lg" id="quote" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <div id="fermer-modal-ajout" data-toggle="modal" data-target=".bd-example-modal-lg" data-backdrop="static">
          <%= link_to add_path do%>
            <i class="fas fa-times"></i>
          <% end  %>
        </div>
        <div class="conteneur-modal-ajout">
          <h1 id='titre-ajout'>Add a quote memory</h1>
          <%= simple_form_for [@memory] do |f| %>
            <div class="row justify-content-center" >
              <div class="col-xs-12 col-md-7">
                <%= f.input :memory_type, input_html: { id: 'special_categorie', value: "quote" }, as: :hidden  %>
                <%= f.input :title, label: 'Your quote' %>
                <%= f.input :description, label: 'Tell me more about this quote' %>
                <%= f.label 'Your stamps*', autofocus: true %>
                <div class="stamps-form">
                  <%= select_tag 'memory[stamps][]', options_for_select(Stamp.all.pluck(:title)), multiple: 'multiple', class: 'form-control select2'%>
                </div>
              </div>
              <div class="submit-add-button">
                <%= f.submit 'Add a memory', class: "btn boutton-rouge boutton-rouge-inside" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:js) do %>
  <script>
    $('#quote').modal('show');
  </script>
<% end %>

app/views/shared/_modalshow.html.erb
<div class="modal fade" id="myModal_<%= memory.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <!-- <div class="modal-header"> -->
        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
        <!-- <h4 class="modal-title" id="myModalLabel">Memory</h4> -->
      <!-- </div> -->
      <div class="modal-body">
        <div class="conteneur-grid">
          <span class="image-grid d-flex align-items-start">
            <% if memory.memory_type == 'spotify' %>
              <div class='player-spotify' id="player-spotify_<%= memory.id %>">
                <i class="fas fa-play-circle" style="font-size: 120px"></i>
              </div>
              <script>
                document.getElementById("player-spotify_<%= memory.id %>").addEventListener("click", (event) => {
                  console.log('test1')
                  fetch("https://api.spotify.com/v1/me/player/play", {
                    method: "PUT",
                    headers: {
                      "Accept": "application/json",
                      "Content-Type": "application/json",
                      "Authorization": "Bearer <%= JSON.parse(current_user.spotify)["access_token"] %>"
                    },
                    body: JSON.stringify({ "uris":["spotify:track:<%= memory.url %>"] })
                  })
                    .then(response => console.log(response))
                });
              </script>
            <% end %>
            <%= link_to '#' do %>
              <% if memory.memory_type == "photo" %>
                <%= cl_image_tag memory.photo, class: "img-fluid", width: 568%>
              <% elsif memory.memory_type == "video" %>
                <%= cl_video_tag(memory.photo.filename, :controls => true, width: 568, crop: :fill) %>
              <% elsif memory.memory_type == "spotify" %>
                <%= image_tag(memory.image_associated, :controls => true, width: 568, crop: :fill) %>
              <% elsif memory.memory_type == "instagram" %>
                <%= image_tag(memory.image_associated, :controls => true, width: 568, crop: :fill) %>
              <% else %>
                <div class="fond-quote">
                  <p> <%= memory.title.capitalize %> </p>
                </div>
              <% end %>
            <% end %>
          </span>
          <span class="edit-delete-grid d-flex align-items-center justify-content-end">
            <div data-toggle="modal" data-target="#myModal_<%= memory.id %>">
              <% if memory.memory_type == "spotify" %>
                <div data-toggle="modal" data-target="#modal-suggestion-spotify-edit_<%= memory.id %>">
                  <i class="fas fa-edit"></i>
                </div>
              <% elsif memory.memory_type == "instagram" %>
                <div data-toggle="modal" data-target="#modal-suggestion-instagram-edit<%= memory.id %>">
                  <i class="fas fa-edit"></i>
                </div>
              <% elsif memory.memory_type == "photo" %>
                <div data-toggle="modal" data-target="#photo-edit_<%= memory.id %>">
                  <i class="fas fa-edit"></i>
                </div>
                <% elsif memory.memory_type == "video" %>
                  <div data-toggle="modal" data-target="#video-edit_<%= memory.id %>">
                    <i class="fas fa-edit"></i>
                  </div>
                <% elsif memory.memory_type == "quote" %>
                  <div data-toggle="modal" data-target="#quote-edit_<%= memory.id %>">
                    <i class="fas fa-edit"></i>
                  </div>
              <% end %>
            </div>
            <%= link_to memory_path(memory), method: :delete do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </span>
            <% unless memory.memory_type == "quote" %>
              <span class="title-grid d-flex align-items-center justify-content-center">
                <h4><%= memory.title.capitalize %></h4>
              </span>
            <% end %>
          <span class="paraph-grid d-flex justify-content-start align-items-center">
            <p> <%= memory.description.capitalize %>
          </p>
          </span>
          <span class="tag-grid d-flex align-items-center justify-content-start">
              <% memory.stamps.each do |stamp|%>
              <div class="stamp-position-bar">
                <div class=<%=stamp.stamp_image%> >
                  <p><%= stamp.title.upcase %></p>
                </div>
              </div>
              <% end%>
          </span>
        </div>
      </div>
      <!-- <div class="modal-footer"> -->
        <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      <!-- </div> -->
    </div>
  </div>
</div>


<% if memory.memory_type == "spotify" %>
  <%= render 'shared/modalsuggespotifyedit', memory: memory %>
<% elsif memory.memory_type == "instagram" %>
  <%= render 'shared/modalsuggeinstagramedit', memory: memory %>
<% elsif memory.memory_type == "photo" %>
  <%= render 'shared/modalphotoedit', memory: memory %>
<% elsif memory.memory_type == "video" %>
  <%= render 'shared/modalvideoedit', memory: memory %>
<% elsif memory.memory_type == "quote" %>
  <%= render 'shared/modalquoteedit', memory: memory %>
<% end %>

app/views/shared/_modalsmall.html.erb
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <%= image_tag "logo.svg" %>
        <h4>Your personnal digital space</h4>
      </div>
      <div class="modal-body">
        <h2>Log in</h2>
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-inputs">
            <%= f.input :email,
                        required: false,
                        autofocus: true,
                        input_html: { autocomplete: "email" } %>
            <%= f.input :password,
                        required: false,
                        input_html: { autocomplete: "current-password" } %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Log in" %>
          </div>
        <% end %>
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modalsuggeinstagram.html.erb
<div class="modal fade bd-example-modal-lg" id="modal-suggestion-instagram<%= memory.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <div id="fermer-modal-ajout" data-toggle="modal" data-target="#modal-suggestion-instagram<%= memory.id %>" data-backdrop="static">
          <i class="fas fa-times"></i>
        </div>
        <div class="conteneur-modal-ajout">
          <h1 id='titre-ajout'>Add a memory</h1>
          <%= simple_form_for Memory.new do |f| %>
            <div class="row">
              <div class="col-md-5">
                <div class="cadre-photo img-fluid" alt="Responsive image">
                  <%= image_tag memory.image_associated %>
                </div>
              </div>
              <div class="col-md-7">
                <%= f.input :memory_type, input_html: {value: f.object.memory_type || memory.memory_type}, as: :hidden  %>
                <%= f.input :image_associated, input_html: {value: f.object.image_associated || memory.image_associated}, as: :hidden  %>
                <%= f.input :url, input_html: {value: f.object.url || memory.likes}, as: :hidden  %>
                <%= f.input :api_id, input_html: {value: f.object.api_id || memory.api_id}, as: :hidden  %>
                <%= f.input :title, input_html: {value: f.object.title || memory.title}, label: 'Location' %>
                <%= f.input :description, input_html: {value: f.object.description || memory.description}, label: 'Caption' %>
                <%= f.label 'Stamps*', autofocus: true %>
                <div class="stamps-form">
                  <%= select_tag 'memory[stamps][]', options_for_select(Stamp.all.pluck(:title)), multiple: 'multiple', class: 'form-control select2', id: "memory_stamps_#{memory.id}"%>
                </div>
              </div>
              <div class="submit-add-button">
                <%= f.submit 'Add a memory', class: "btn boutton-rouge boutton-rouge-inside" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modalsuggeinstagramedit.html.erb
<div class="modal fade bd-example-modal-lg" id="modal-suggestion-instagram-edit<%= memory.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <div id="fermer-modal-ajout" data-toggle="modal" data-target="#modal-suggestion-instagram<%= memory.id %>" data-backdrop="static">
          <i class="fas fa-times"></i>
        </div>
        <div class="conteneur-modal-ajout">
          <h1 id='titre-ajout'>Edit a memory</h1>
          <%= simple_form_for Memory.find(memory.id) do |f| %>
            <div class="row">
              <div class="col-md-5">
                <div class="cadre-photo img-fluid" alt="Responsive image">
                  <%= image_tag memory.image_associated %>
                </div>
              </div>
              <div class="col-md-7">
                <%= f.input :memory_type, input_html: {value: f.object.memory_type || memory.memory_type}, as: :hidden  %>
                <%= f.input :image_associated, input_html: {value: f.object.image_associated || memory.image_associated}, as: :hidden  %>
                <%= f.input :url, input_html: {value: f.object.url || memory.url}, as: :hidden  %>
                <%= f.input :api_id, input_html: {value: f.object.api_id || memory.api_id}, as: :hidden  %>
                <%= f.input :title, input_html: {value: f.object.title || memory.title}, label: 'Location' %>
                <%= f.input :description, input_html: {value: f.object.description || memory.description}, label: 'Caption' %>
                <%= f.label 'Stamps*', autofocus: true %>
                <div class="stamps-form">
                  <select multiple="multiple" name="memory[stamps][]" id="memory_stamps_<%= memory.id %>" class="form-control select2">
                    <% memory.stamps.each do |stamp| %>
                      <option selected value="<%= stamp.title %>"><%= stamp.title %></option>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="submit-add-button">
                <%= f.submit 'Edit a memory', class: "btn boutton-rouge boutton-rouge-inside" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modalsuggespotify.html.erb
<div class="modal fade bd-example-modal-lg" id="modal-suggestion-spotify_<%= memory.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <div id="fermer-modal-ajout" data-toggle="modal" data-target="#modal-suggestion-spotify_<%= memory.id %>" data-backdrop="static">
          <i class="fas fa-times"></i>
        </div>
        <div class="conteneur-modal-ajout">
          <h1 id='titre-ajout'>Add a memory</h1>
          <%= simple_form_for Memory.new do |f| %>
            <div class="row">
              <div class="col-md-5">
                <div class="cadre-photo img-fluid" alt="Responsive image">
                  <%= image_tag memory.image_associated %>
                </div>
              </div>
              <div class="col-md-7">
                <%= f.input :memory_type, input_html: {value: f.object.memory_type || memory.memory_type}, as: :hidden  %>
                <%= f.input :image_associated, input_html: {value: f.object.image_associated || memory.image_associated}, as: :hidden  %>
                <%= f.input :url, input_html: {value: f.object.url || memory.url}, as: :hidden  %>
                <%= f.input :api_id, input_html: {value: f.object.api_id || memory.api_id}, as: :hidden  %>
                <%= f.input :title, input_html: {value: f.object.title || memory.title}, label: 'Artist' %>
                <%= f.input :description, input_html: {value: f.object.description || memory.description}, label: 'Track' %>
                <%= f.label 'Stamps*', autofocus: true %>
                <div class="stamps-form">
                  <%= select_tag 'memory[stamps][]', options_for_select(Stamp.all.pluck(:title)), multiple: 'multiple', class: 'form-control select2', id: "memory_stamps_#{memory.id}" %>
                </div>
              </div>
              <div class="submit-add-button">
                <%= f.submit 'Add a memory', class: "btn boutton-rouge boutton-rouge-inside" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modalvideo.html.erb
<!-- MODAL VIDEO -->

<div class="modal fade bd-example-modal-lg" id="video" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <div id="fermer-modal-ajout" data-toggle="modal" data-target=".bd-example-modal-lg" data-backdrop="static">
          <%= link_to add_path do%>
            <i class="fas fa-times"></i>
          <% end  %>
        </div>
        <div class="conteneur-modal-ajout">
          <h1 id='titre-ajout'>Add a video memory</h1>
          <%= simple_form_for [@memory] do |f| %>
            <div class="row justify-content-center">
              <div class="col-xs-12 col-md-7">
                <%= f.input :memory_type, input_html: { id: 'special_categorie', value: "video" }, as: :hidden  %>
                <%= f.input :title, label: 'Your video name' %>
                <%= f.input :description, label: 'Tell me more about this video' %>
                <%= f.label 'Your stamps*', autofocus: true %>
                <div class="stamps-form">
                  <%= select_tag 'memory[stamps][]', options_for_select(Stamp.all.pluck(:title)), multiple: 'multiple', class: 'form-control select2'%>
                </div>
                <%= f.input :photo, label: 'Upload your video' %>
                <%= f.input :photo_cache, as: :hidden %>
              </div>
              <div class="submit-add-button">
                <%= f.submit 'Add a memory', class: "btn boutton-rouge boutton-rouge-inside" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:js) do %>
  <script>
    $('#video').modal('show');
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <% if user_signed_in? %>

    <div class="navbar-wagon-left">
      <!-- Logo -->
      <%= link_to root_path do %>
        <%= image_tag "logo.svg" %>
      <% end %>
      <div class="navbar-searchbar d-none d-lg-block d-xl-block">
        <%= render 'shared/searchbar' %>
      </div>
    </div>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right d-none d-md-flex">

      <!-- Links when logged in -->
      <% if ((params["controller"] == "memboard") || ((params["controller"] == "memories") && ((params["action"] == "index") || (params["action"] == "show")))) %>
        <%= link_to "Explore", memboard_path, class: "btn boutton-rouge boutton-rouge-border" %>
        <%= link_to "Add a memory", add_path, class: "btn boutton-rouge boutton-rouge-inside", id: "add" %>
      <% else %>
        <%= link_to "Explore", memboard_path, class: "btn boutton-rouge boutton-rouge-inside" %>
        <%= link_to "Add a memory", add_path, class: "btn boutton-rouge boutton-rouge-border", id: "add" %>
      <% end %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.profile_picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown", gravity: :face %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <span><i class="fas fa-user"></i> Profile</span>
              <% end %>
            </li>
            <li>
              <%= link_to databoard_path do %>
                <span><i class="fas fa-chart-line"></i> Databoard</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: " Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item d-block d-md-none">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to memboard_path do %>
            <span><i class="fas fa-search"></i>Explore</span>
            <% end %>
          </li>
          <li>
            <%= link_to add_path do %>
            <span><i class="fas fa-plus-circle"></i>Add a memory</span>
            <% end %>
          </li>
          <li><%= link_to profile_path do %>
                  <span><i class="fas fa-user"></i> Profile</span>
                <% end %></li>
          <li>
            <%= link_to databoard_path do %>
              <span><i class="fas fa-chart-line"></i> Databoard</span>
            <% end %>
          </li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: " Log out") %>
                <% end %></li>
        </ul>
      </div>
    </div>

  <% else %>
      <!-- Logo -->
    <%= link_to root_path do %>
      <%= image_tag "logo.svg" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right d-none d-md-flex">
      <!-- Login link (when logged out) -->
      <div class="button-container">
        <%= link_to "Sign In", "users/sign_in", class: "btn boutton-rouge boutton-rouge-inside sign" %>
      </div>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item d-block d-md-none">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "users/sign_in" do %>
            <span><i class="fas fa-sign-in-alt"></i> Sign In</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

  <% end %>
</div>

app/views/shared/_profile_banner.html.erb
<div class="profile-banner">
  <div class="conteneur-profile-banner">
    <h2>Connect your @ccounts <%= @test %></h2>
    <h3 class="d-none d-lg-block">Click on one of the icon to connect your account to your Life Pod</h3>
    <div class="row">
      <div class="offset-md-2 col-md-2 col-xs-6">
        <div class="card-profile-logo">
          <%= link_to @url_spotify do %>
            <% if current_user.spotify.nil? %>
              <%= image_tag 'spotify_logo_nb.png', id: "profile-banner-logo-spotify" %>
            <% else %>
              <%= image_tag 'spotify_logo.png', id: "profile-banner-logo-spotify" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-2 col-xs-6">
        <div class="card-profile-logo">
          <%= link_to @url_instagram do %>
            <% if current_user.instagram.nil? %>
              <%= image_tag 'instagram_logo_nb.png', id: "profile-banner-logo-insta" %>
            <% else %>
              <%= image_tag 'instagram_logo.png', id: "profile-banner-logo-insta" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-2 col-xs-6">
        <div class="card-profile-logo">
          <% if current_user.facebook.nil? %>
            <%= image_tag 'facebook_logo_nb.png', id: "profile-banner-logo-fb" %>
          <% else %>
            <%= image_tag 'facebook_logo.png', id: "profile-banner-logo-fb" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-2 col-xs-6">
        <div class="card-profile-logo">
          <% if current_user.youtube.nil? %>
            <%= image_tag 'youtube_logo_nb.png', id: "profile-banner-logo-youtube" %>
          <% else %>
            <%= image_tag 'youtube_logo.png', id: "profile-banner-logo-youtube" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>