config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'memories/add', to: 'pages#add', as: :add
  get 'memories/board', to: 'memboard#board', as: :memboard
  get 'memories/profile', to: 'pages#profile', as: :profile

  get 'memories/databoard', to: 'pages#databoard', as: :databoard

  get 'memories/add/photo', to: 'pages#photo', as: :modal_photo
  get 'memories/add/video', to: 'pages#video', as: :modal_video
  get 'memories/add/quote', to: 'pages#quote', as: :modal_quote


  resources :memories, only: [:index, :create, :edit, :update, :destroy] do
    resources :stamps, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'test', to: 'pages#test'
  get 'test2', to: 'pages#test2'
  get 'test3', to: 'pages#test3'

end

app/controllers/memboard_controller.rb
class MemboardController < ApplicationController
  def board
    @memories = policy_scope(Memory)
    # je selectionne toutes les combinaisons de 2 stamps
    # je trie mon array d'id de stamps en fonction de leur nombre de memories
    @stamps = policy_scope(Stamp)
         .pluck(:id)
         .combination(2)
         .to_a
         .sort_by { |stamp| Memory.joins(:stamps).where(stamps: { id: [stamp[0], stamp[1]] }).group(:id).having("count(*) > 1").distinct.count.length }
         .reverse
         .first(10)
         .map { |id| Stamp.find(id) }
  end

  private

  def pertinent_stamps
    # algorithme de pertinence a definir
    return Stamp.all
  end
end

app/views/memboard/board.html.erb
<%= render 'shared/dashboard' %>

<div class="conteneur-explore"><h1 class="text-center font-weight-bold">Explore your memories</h1></div>
  <div class="wrapper-box">
    <div class="block">
      <div class="animation">
        <% compteur = 1 %>
        <% @stamps.each do |pair|%>
        <% if compteur == 1 %>
          <div class="first ecart-box">
        <% else %>
          <div class="ecart-box">
        <% end %>
            <% compteur -= 1 %>
            <div class="box">
              <%= image_tag "boxes/#{rand(1...4)}.svg" %>
                <div class="<%=pair[0].stamp_image%> stamp-right" >
                  <div class="stamp-content">
                    <p><%= pair[0].title.upcase %></p>
                  </div>
                </div>
              <div class="">
                <div class="<%= pair[1].stamp_image%> stamp-left" >
                  <p><%= pair[1].title.upcase %></p>
                </div>
              </div>
            </div>
            <span class="lien-to-box">
              <%= link_to "Explore it", memories_path(stamp: [pair[0].title, pair[1].title]), class: "btn boutton-rouge boutton-rouge-border" %>
            </span>
          </div>
        <% end %>
      </div>
    </div>
  </div>



<%= javascript_pack_tag 'carroussel' %>