config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'memories/add', to: 'pages#add', as: :add
  get 'memories/board', to: 'memboard#board', as: :memboard
  get 'memories/profile', to: 'pages#profile', as: :profile

  get 'memories/databoard', to: 'pages#databoard', as: :databoard

  get 'memories/add/photo', to: 'pages#photo', as: :modal_photo
  get 'memories/add/video', to: 'pages#video', as: :modal_video
  get 'memories/add/quote', to: 'pages#quote', as: :modal_quote


  resources :memories, only: [:index, :create, :edit, :update, :destroy] do
    resources :stamps, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'test', to: 'pages#test'
  get 'test2', to: 'pages#test2'
  get 'test3', to: 'pages#test3'

end

app/views/pages/add.html.erb
<div class="conteneur-memories" id="container">
  <h1 class="text-center font-weight-bold d-none d-md-block">Here is the best content we have selected for you</h1>
</div>

<div class="row">
  <div class="d-none d-md-block col-md-2">
  </div>

  <div class="col-xs-4 col-sm-10 col-md-8">
    <div class="card-columns">
      <div class="card card-pola" id="versCategories">
        <div class="image-container">
          <div class="card-img" id="fixed">
            <h3 class="text-center font-weight-bold">Add a memory from another source</h3>
          </div>
        </div>
        <div class="card-body">
          <p class="card-text">Add your <strong>personal content</strong></p>
        </div>
      </div>
      <% unless @memories.nil? %>
        <% @memories.each do |memory|%>
          <% if memory.memory_type == "spotify" %>
            <div class="card">
              <div class="card-pola">
                <div class="image-container" data-toggle="modal" data-target="#modal-suggestion-spotify_<%= memory.id %>">
                  <%= image_tag memory.image_associated, class: "card-img flex"%>
                  <h2><%= memory.description %></h2>
                  <h3><%= memory.title.capitalize %></h3>
                    <%= image_tag "spotify-blanc-2.svg", class: "center" %>
                </div>
                <div class="card-body">
                  <p>Suggested from <strong>Spotify</strong></p>
                  <p><strong>Top 50</strong> listenings</p>
                </div>
              </div>
            </div>
          <% elsif memory.memory_type == "instagram" %>
            <div class="card">
              <div class="card-pola">
                <div class="image-container" data-toggle="modal" data-target="#modal-suggestion-instagram<%= memory.id %>">
                  <%= image_tag memory.image_associated, id: "box", class: "card-img"%>
                  <h3><%= memory.title.capitalize %></h3>
                  <%= image_tag "instagram-blanc-2.svg", class: "center2" %>
                </div>
                  <div class="card-body">
                    <p>Suggested from <strong>Instagram</strong></p>
                    <p><strong>Liked <%= memory.url %> times</strong></p>
                  </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end%>
    </div>
  </div>






  <div class="d-none d-md-block col-md-2">
  </div>

</div>

<%= render 'shared/footerbleu' %>

<%= render 'shared/smallfooterbleu' %>

<% unless @memories.nil? %>
  <% @memories.each do |memory|%>
    <% if memory.memory_type == "spotify" %>
      <%= render 'shared/modalsuggespotify', memory: memory %>
    <% elsif memory.memory_type == "instagram" %>
      <%= render 'shared/modalsuggeinstagram', memory: memory %>
    <% end %>
  <% end %>
<% end %>



<%= javascript_pack_tag 'smallFooter' %>
<%= javascript_pack_tag 'footer' %>

app/views/pages/dashboard.html.erb
<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load Charts and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Draw the pie chart for Sarah's pizza when Charts is loaded.
      google.charts.setOnLoadCallback(drawManuPieChart);

      // Draw the pie chart for the Anthony's pizza when Charts is loaded.
      google.charts.setOnLoadCallback(drawSuggestedPieChart);

      google.charts.setOnLoadCallback(drawManuSuggestedPieChart);

      google.charts.setOnLoadCallback(drawNumberSuggestedChart);


      // Callback that draws the pie chart for Sarah's pizza.
      function drawManuPieChart() {

        // Create the data table for Sarah's pizza.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Nature');
        data.addColumn('number', 'Memories');
        data.addRows([
          ['Photos', 246],
          ['Videos', 89],
          ['Quotes', 56]
        ]);

        // Set options for Sarah's pie chart.
        var options = {title:'Your manually-added memories repartition',
                       width:400,
                       height:300,
                       colors: ['#45315d', '#ff2400', '#ff9280']};

        // Instantiate and draw the chart for Sarah's pizza.
        var chart = new google.visualization.PieChart(document.getElementById('Manu_Pie_chart_div'));
        chart.draw(data, options);
      }

      // Callback that draws the pie chart for Anthony's pizza.
      function drawSuggestedPieChart() {

        // Create the data table for Anthony's pizza.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Nature');
        data.addColumn('number', 'Memories');
        data.addRows([
          ['Spotify', 356],
          ['Instagram', 148]
        ]);

        // Set options for Anthony's pie chart.
        var options = {title:'Your suggested memories repartition',
                       width:400,
                       height:300,
                       colors: ['#45315d', '#ff2400']};

        // Instantiate and draw the chart for Anthony's pizza.
        var chart = new google.visualization.PieChart(document.getElementById('Suggested_Pie_chart_div'));
        chart.draw(data, options);
      }

      function drawManuSuggestedPieChart() {

        // Create the data table for Sarah's pizza.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Nature');
        data.addColumn('number', 'Memories');
        data.addRows([
          ['Manual', 391],
          ['Suggested', 504]
        ]);

        // Set options for Sarah's pie chart.
        var options = {title:'Your manually/suggested repartition',
                       width:400,
                       height:300,
                       colors: ['#45315d', '#ff2400']};

        // Instantiate and draw the chart for Sarah's pizza.
        var chart = new google.visualization.PieChart(document.getElementById('Manu_Suggested_Pie_chart_div'));
        chart.draw(data, options);
      }

      function drawNumberSuggestedChart() {


        var data = google.visualization.arrayToDataTable([
                  ['Year', 'Sales'],
                  ['2013',  1000],
                  ['2014',  1170],
                  ['2015',  660],
                  ['2016',  1030],
                  ['2013',  1000],
                  ['2014',  1170],
                  ['2015',  660],
                  ['2016',  1030]
                ]);


        var options = {
          title: 'Number of memories added',
          hAxis: {title: 'Year',  titleTextStyle: {color: '#333'}},
          vAxis: {minValue: 0},
          colors: ['#0b132b']
        };

        var chart = new google.visualization.AreaChart(document.getElementById('Number_Suggested_Chart_div'));
        chart.draw(data, options);
      }

    </script>
  </head>
  <body>

  <div class="conteneur-memories" id="container">
    <h1 class="text-center font-weight-bold d-none d-md-block">Your dashboard</h1>
  </div>


    <!--Number of boxes-->

    <div class="large-container grey">
      <div class="num-box">
        <%= image_tag "boxes/1.svg", class: "padding"%>
        <div class="wrap text-center">
          <h3>You would need <%= pluralize @tot_box, "box" %> to move all your content out !</h3>
        </div>
      </div>
    </div>
    <!--Podium-->

    <div class="large-container">
      <div class="row">
        <div class="col-lg">
          <h2 class="text-center espace">Your most used stamps</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-2 offset-lg-3"">
          <div class="box-viz">
            <div class="icon">
              <div class=<%=@stamp_1.stamp_image%> >
                <p><%= @stamp_1.title.upcase %></p>
              </div>
            </div>
            <div class="count">
              <p><strong><%=@stamp_1_mem%></strong></p>
              <p><%=  "Memory".pluralize(@stamp_1_mem) %></p>
            </div>
          </div>
        </div>
        <div class="col-lg-2">
          <div class="box-viz">
            <div class="icon">
              <div class=<%=@stamp_2.stamp_image%> >
                <p><%= @stamp_2.title.upcase %></p>
              </div>
            </div>
            <div class="count">
              <p><strong><%=@stamp_2_mem%></strong></p>
              <p><%=  "Memory".pluralize(@stamp_2_mem) %></p>
            </div>
          </div>
        </div>
        <div class="col-lg-2">
          <div class="box-viz">
            <div class="icon">
              <div class=<%=@stamp_3.stamp_image%> >
                <p><%= @stamp_3.title.upcase %></p>
              </div>
            </div>
            <div class="count">
              <p><strong><%=@stamp_3_mem%></strong></p>
              <p><%=  "Memory".pluralize(@stamp_2_mem) %></p>
            </div>
          </div>
        </div>
      </div>
    </div>








    <!--Table and divs that hold the pie charts-->
    <table class="columns">
      <tr>
        <td><div id="Manu_Pie_chart_div" style="border: 1px solid #ccc"></div></td>
        <td><div id="Suggested_Pie_chart_div" style="border: 1px solid #ccc"></div></td>
        <td><div id="Manu_Suggested_Pie_chart_div" style="border: 1px solid #ccc"></div></td>
      </tr>
      <tr>
        <div id="Number_Suggested_Chart_div" style="width: 100%; height: 500px;"></div>
      </tr>
    </table>


  </body>
</html>

app/views/pages/databoard.html.erb
<h2 class="text-center font-weight-bold d-none d-md-block" style="margin-top: 20px; margin-bottom: 10px;"><%= current_user.first_name %>'s dashboard</h1>



<div class="conteneur-grid-data">

  <!--Piecharts-->
  <span class= "piechart-grid d-flex align-items-center">
    <div class="conteneur-graph-pie">
      <p style="text-align: center; margin: 8px 0px; font-style: italic;">Self-added memories distribution</p>
      <canvas id="ManuPieChart" data-tab="<%= Memory.where(memory_type: 'photo').count %>-<%= Memory.where(memory_type: 'video').count %>-<%= Memory.where(memory_type: 'quote').count %>"></canvas>
    </div>
    <div class="conteneur-graph-pie">
      <p style="text-align: center; margin: 8px 0px; font-style: italic;">Added through suggestion memories distribution</p>
      <canvas id="SuggePieChart" data-tab="<%= Memory.where(memory_type: 'spotify').count %>-<%= Memory.where(memory_type: 'instagram').count %>"></canvas>
    </div>
    <div class="conteneur-graph-pie">
      <p style="text-align: center; margin: 8px 0px; font-style: italic;">Self-added VS Suggested distribution</p>
      <canvas id="ManuSuggePieChart" data-tab="<%= Memory.where(memory_type: 'spotify').count + Memory.where(memory_type: 'instagram').count %>-<%= Memory.where(memory_type: 'photo').count + Memory.where(memory_type: 'video').count + Memory.where(memory_type: 'quote').count %>"></canvas>
    </div>
  </span>

  <!--Date d'ajout-->
  <span class="line-chart-grid">
    <div class="conteneur-graph">
      <p style="text-align: center; margin: 4px 0px; font-style: italic;">Number of addings per period of time</p>
      <canvas id="line-chart" data-tab="12-21-3-21-32-33-22-12-40"></canvas>
    </div>
  </span>



  <!--Pertinence des sukG-->

  <span class="bar-chart-grid">
    <div class="conteneur-graph">
      <p style="text-align: center; margin: 4px 0px; font-style: italic;">Suggestion efficiency</p>
      <canvas id="SpotInstaBarChart" data-tab="<%= @sukg_instagram %>-<%= @sukg_spotify %>"></canvas>
    </div>
  </span>


  <!--Podium-->

  <span class="podium-grid">
    <div class="conteneur-podium-grid">

      <span class="title-podium-grid align-items-center">
        <h4 class="text-center espace" style="margin-bottom: 20px; margin-top: 10px;">Your most used stamps</h4>
      </span>

      <span class="stamp-1-grid d-flex align-items-center justify-content-center">
        <div class="icon">
          <div class=<%=@stamp_1.stamp_image%> >
            <p><%= @stamp_1.title.upcase %></p>
          </div>
        </div>
      </span>
      <span class="count-1-grid d-flex align-items-center justify-content-center">
        <p style="font-size: 36px; font-weight: bold; margin-bottom: 0px;"><%=@stamp_1_mem%></p>
        <p><%=  "Memory".pluralize(@stamp_1_mem) %></p>
      </span>
      <span class="medal-1-grid d-flex align-items-end justify-content-center">
        <%= image_tag 'gold-medal.png' %>
      </span>

      <span class="stamp-2-grid d-flex align-items-center justify-content-center">
        <div class="icon">
          <div class=<%=@stamp_2.stamp_image%> >
            <p><%= @stamp_2.title.upcase %></p>
          </div>
        </div>
      </span>
      <span class="count-2-grid d-flex align-items-center justify-content-center">
        <p style="font-size: 36px; font-weight: bold; margin-bottom: 0px;"><%=@stamp_2_mem%></p>
        <p><%=  "Memory".pluralize(@stamp_2_mem) %></p>
      </span>
      <span class="medal-2-grid d-flex align-items-end justify-content-center">
        <%= image_tag 'silver-medal.png' %>
      </span>

      <span class="stamp-3-grid d-flex align-items-center justify-content-center">
        <div class="icon">
          <div class=<%=@stamp_3.stamp_image%> >
            <p><%= @stamp_3.title.upcase %></p>
          </div>
        </div>
      </span>
      <span class="count-3-grid d-flex align-items-center justify-content-center">
        <p style="font-size: 36px; font-weight: bold; margin-bottom: 0px;"><%=@stamp_3_mem%></p>
        <p><%=  "Memory".pluralize(@stamp_2_mem) %></p>
      </span>
      <span class="medal-3-grid d-flex align-items-end justify-content-center">
        <%= image_tag 'bronze-medal.png' %>
      </span>

    </div>
  </span>




  <!--Number of boxes-->

  <span class="box-fun-grid">
    <div class="num-box">
      <%= image_tag "boxes/1.svg", class: "padding"%>
      <div class="wrap text-center">
        <h3>You would need </h3>
        <h3><%= pluralize @tot_box, "box" %></h3>
        <h3>to move all your content</h3>
        <p>Considering that you would need 400 musics, 400 videos, 1600 quotes and 6400 photos to fill a box.</p>
      </div>
    </div>
  </span>

</div>

app/views/pages/home.html.erb
<div class="banner blue">
  <div class="banner-content">
    <h1>Your personal digital space</h1>
    <p class="d-none d-lg-block"><span id="banner-typed-text"></span></p>
    <%= image_tag "Boxes.svg", id: "boxes", class: "d-none d-lg-block"%>
  </div>
</div>

<section>
  <h1 class="font-weight-bold">Discover</h1>
  <button id="discover"></button>
</section>

<div class="large-container grey">
  <div class="wrapper">
      <div class="container-box-left red">
      <h1>1.</h1>
      <p>Connect all your accounts to your personal storage.</p>
    </div>
    <div class="container-right margin d-none d-xl-block">
      <%= image_tag "logo-accounts.svg"%>
    </div>
  </div>
</div>

<div class="large-container">
  <div class="wrapper">
    <div class="container-left d-none d-xl-block">
      <div>
        <%= image_tag "stamps.svg"%>
      </div>
    </div>
    <div class="container-box-right violet">
      <h1>2.</h1>
      <p>Stamp your memories to identify them. The most the better !</p>
    </div>
  </div>
</div>

<div class="large-container grey">
  <div class="wrapper">
    <div class="container-box-left saumon">
      <h1>3.</h1>
      <p>Find & Explore your best memories.</p>
    </div>
    <div class="container-right d-none d-xl-block">
      <%= image_tag "group-boxes.svg"%>
    </div>
  </div>
</div>

<div class="button-container">
  <%= link_to "Sign Up", "users/sign_up", class: "btn boutton-rouge boutton-rouge-inside sign" %>
</div>

    <%= javascript_pack_tag 'banner' %>
    <%= javascript_pack_tag 'discover' %>

app/views/pages/photo.html.erb
<div class="conteneur-memories" id="container">
  <h1 class="text-center font-weight-bold">Here is the best content we have selected for you</h1>
</div>

<div class="row">
  <div class="d-none d-md-block col-md-2">
  </div>

  <div class="col-xs-12 col-sm-10 col-md-8">
    <div class="card-columns">
      <div class="card card-pola" id="versCategories">
        <div class="image-container">
          <div class="card-img" id="fixed">
            <h3 class="text-center font-weight-bold">Add a memory from another source</h3>
          </div>
        </div>
        <div class="card-body">
          <p class="card-text">Add your <strong>personal content</strong></p>
        </div>
      </div>
      <% unless @spotify_memories.nil? %>
        <% @spotify_memories.each do |memory|%>
          <div class="card">
            <div class="card-pola">
              <div class="image-container" data-toggle="modal" data-target="#modal-suggestion-spotify_<%= memory.id %>">
                <%= image_tag memory.image_associated, id: "box", class: "card-img"%>
                <h2><%= memory.description %></h2>
                <h3><%= memory.title.capitalize %></h3>
                <div class="card-img-overlay">
                  <i class="fas fa-compact-disc"></i>
                </div>
              </div>
              <div class="card-body">
                <p>Suggested from <strong>Spotify</strong></p>
                <p><strong>Top 50</strong> listenings</p>
              </div>
            </div>
          </div>
        <% end%>
      <% end%>
    </div>
  </div>

  <div class="d-none d-md-block col-md-2">
  </div>

</div>

<div class="small-display-categories d-none d-md-block" id="mySmallFooter">
  <div class="small-conteneur-ajout">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-4">
            <div class="small-item-categories" data-categorie="photo">
              <i class="fas fa-image selected-picto"></i>
            </div>
          </div>
          <div class="col-md-4">
            <div class="small-item-categories" data-categorie="video">
              <%= link_to modal_video_path do%>
                <i class="fas fa-video"></i>
              <% end  %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="small-item-categories" data-categorie="quote">
              <%= link_to modal_quote_path do%>
                <i class="fas fa-quote-right"></i>
              <% end  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- MODAL PHOTO -->

<%= render 'shared/modalphoto' %>

app/views/pages/profile.html.erb
<%= render 'shared/profile_banner' %>

<div class="conteneur-profile-page">
  <div class="row">
    <div class="col-xs-12 offset-md-1 col-md-3">
      <div class="profile-picture">
        <%= cl_image_tag current_user.profile_picture, class: 'profile-picture-big' %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn boutton-rouge boutton-rouge-inside" %>
      </div>
    </div>
    <div class="col-xs-12 offset-md-1 col-md-6">
      <div class="profile-informations-personnelles">
        <h3>Your personal information</h3>
        <p>Email address: <%= current_user.email %></p>
        <p>First name: <%= current_user.first_name %></p>
        <p>Last name: <%= current_user.last_name %></p>
        <p>Birth date: <%= current_user.birth_date %></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/quote.html.erb
<div class="small-display-categories d-none d-md-block" id="mySmallFooter">
  <div class="small-conteneur-ajout">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-4">
            <div class="small-item-categories" data-categorie="photo">
              <%= link_to modal_photo_path do%>
                <i class="fas fa-image"></i>
              <% end  %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="small-item-categories" data-categorie="video">
              <%= link_to modal_video_path do%>
                <i class="fas fa-video"></i>
              <% end  %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="small-item-categories" data-categorie="quote">
              <i class="fas fa-quote-right selected-picto"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- MODAL QUOTE -->

<%= render 'shared/modalquote' %>

app/views/pages/test2.html.erb
<h1 style="color: #FF9280">Spotify Web Playback SDK Quick Start Tutorial</h1>
<h1 style="color: rgba(255, 146, 128, 1)">Spotify Web Playback SDK Quick Start Tutorial</h1>
<h2>Open your console log: <code>View > Developer > JavaScript Console</code></h2>

<script src="https://sdk.scdn.co/spotify-player.js">

</script>
<!-- We will insert our code here. -->

app/views/pages/test3.html.erb
<!-- Small modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Small modal</button>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <%= image_tag "logo.svg" %>
        <h4>Your personnal digital space</h4>
      </div>
      <div class="modal-body">
        <h2>Log in</h2>
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-inputs">
            <%= f.input :email,
                        required: false,
                        autofocus: true,
                        input_html: { autocomplete: "email" } %>
            <%= f.input :password,
                        required: false,
                        input_html: { autocomplete: "current-password" } %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Log in" %>
          </div>
        <% end %>
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/video.html.erb
<div class="small-display-categories d-none d-md-block" id="mySmallFooter">
  <div class="small-conteneur-ajout">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-4">
            <div class="small-item-categories" data-categorie="photo">
              <%= link_to modal_photo_path do%>
                <i class="fas fa-image"></i>
              <% end  %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="small-item-categories" data-categorie="video">
              <i class="fas fa-video selected-picto"></i>
            </div>
          </div>
          <div class="col-md-4">
            <div class="small-item-categories" data-categorie="quote">
              <%= link_to modal_quote_path do%>
                <i class="fas fa-quote-right"></i>
              <% end  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- MODAL VIDEO -->

<%= render 'shared/modalvideo' %>